Skripsi
ftisunpar/BlueTape pull request #10
Opened 2017-04-18 03:22 UTC by AdrianReynaldi

Pembangkit jadwal dosen

2017-05-02 08:10 UTC, pascalalfadian requested changes

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/config/modules.php
> +	'LihatJadwalDosen' => array('root', 'mahasiswa.it', 'dosen.it')
Please rename `it` to `informatika` (for dosen & mahasiswa)

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/config/modules.php
> +    'PerubahanKuliahManage' => 'Manajemen Perubahan Kuliah',
Open project in NetBeans PHP, then for all changed files, reformat the code (Ctrl+Shift+R or Alt+Shift+R)

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/controllers/EntriJadwalDosen.php
> +		//$this->session->set_userdata('request_add_jadwal',$data);
Please remove unused codes

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/views/EntriJadwalDosen/main.php
> +							<option value="1"> 1 jam </option>
Gunakan for untuk 1-9 jam

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/views/EntriJadwalDosen/main.php
> +							<option value="7"> 07:00 </option>
Gunakan for untuk menulis jam 7 sampai 16

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/views/EntriJadwalDosen/main.php
> +							<option> Senin </option>
Gunakan value=0 untuk Senin .. value=4 untuk Jumat. Di database juga simpan seperti demikian.

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/controllers/LihatJadwalDosen.php
> +		public function hari_ke_kolom($hari){
Dua fungsi ini mohon pindahkan ke Model

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/models/JadwalDosen_model.php
> +
Buat konstanta hari, kurang lebih seperti ini:

```php
const DAY_NAMES = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'];
```

Seluruh nama hari harus mengacu dari konstanta ini.

2017-05-02 08:10 UTC, pascalalfadian commented on www/application/views/templates/script_foundation.php
> +<script src="/public/js/app.js"></script>
Coba masuk ke file ini, di baris terakhir tekan enter satu kali.

2017-05-02 08:13 UTC, pascalalfadian approved these changes

2017-05-02 08:20 UTC, pascalalfadian requested changes

2017-05-02 08:20 UTC, pascalalfadian commented on www/application/config/modules.php
> +	'dosen.ftis' => array ('cheni@unpar.ac.id', 'mariskha@unpar.ac.id', 'nico@unpar.ac.id', 'anung@unpar.ac.id', 'moertini@unpar.ac.id', 'aditya-bagoes@unpar.ac.id', 'chandraw@unpar.ac.id', 'elisatih@un
Please rename `ftis` to `informatika`.

2017-05-04 05:59 UTC, AdrianReynaldi commented on www/application/models/JadwalDosen_model.php
> +
menggunakan konstanta di model memunculkan eror "undefined constants in www/index.php" ,dan benar begitu saya simpan konstantanya di index.php erornya hilang. Apakah tidak apa-apa bila saya menyimpan konstatnanya di index.php, bukan di model ?

2017-05-04 07:14 UTC, pascalalfadian commented on www/application/models/JadwalDosen_model.php
> +
Jangan, karena scope DAY_NAMES ini adanya di model. Ikuti cara/sintaks [ini](http://php.net/manual/en/language.oop5.constants.php) bisa? Kalau tidak bisa, kembalikan saja pakai cara kamu yang sebelumnya.

2017-05-05 02:44 UTC, pascalalfadian approved these changes

2017-05-05 02:46 UTC, merged