adding notification email for the Transcript Requestor
ftisunpar/BlueTape pull request #21
Opened 2017-10-17 16:50 UTC by chez14

I've added some methods to the `Transcript_model` to easily get information based on its ID, is it ok to do it?

2017-10-18 23:15 UTC, pascalalfadian requested changes
Ahh... I think I have to submit my review first.

2017-10-18 23:15 UTC, pascalalfadian commented on www/application/models/Transkrip_model.php
> +    public function requestsByID($id, $rows = NULL, $start = NULL) {
Since it will only returns exactly one request, please:

* rename to `requestByID()` (without `s`)
* return not an array, but an object of that single transkrip request (so the caller does not need to access index `0`)

2017-10-19 01:35 UTC, pascalalfadian commented
Just... one.. more.. thing..

> return not an array, but an object of that single transkrip request (so the caller does not need to access index 0)

You just need to move `[0]` to inside `requestByID()` function.

2017-10-19 03:37 UTC, chez14 commented
oh lol, I forgot that the model should've return non-array object xD

2017-10-19 05:01 UTC, pascalalfadian approved these changes

2017-10-19 05:01 UTC, merged